# workflow name
name: Generate release-artifacts

# on events
on:
  push:
    tags: 
        - "*.*"

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2
      - name: Generate build files
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.18
          dest: build
          pkg: "cmd/encarno"
          prefix: ${{ github.event.repository.name }}
          targets: linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          buildvcs: ""
      - name: Release artifacts
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: > 
            build/${{ github.event.repository.name }}-linux-amd64,
            build/${{ github.event.repository.name }}-linux-arm64,
            build/${{ github.event.repository.name }}-darwin-amd64,
            build/${{ github.event.repository.name }}-darwin-arm64,
            build/${{ github.event.repository.name }}-windows-amd64.exe
          allowUpdates: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
